# Generated by Django 3.2.6 on 2021-09-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0003_auto_20210904_0102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='password',
            new_name='reg_confirm_pass',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='email',
            new_name='reg_email',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='reg_first_name',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='passwordr',
            new_name='reg_password',
        ),
        migrations.AddField(
            model_name='register',
            name='reg_last_name',
            field=models.CharField(default='SOME STRING', max_length=150),
        ),
    ]
