# Generated by Django 3.2.6 on 2021-09-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0004_auto_20210904_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dreg_first_name', models.CharField(max_length=150)),
                ('dreg_last_name', models.CharField(default='SOME STRING', max_length=150)),
                ('dreg_email', models.CharField(max_length=200)),
                ('dreg_password', models.CharField(max_length=20)),
                ('dreg_date_of_birth', models.CharField(max_length=20)),
                ('dreg_phone_number', models.IntegerField(max_length=20)),
            ],
        ),
    ]
