# Generated by Django 3.2.6 on 2021-09-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodbank_app', '0005_donorregister'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donorregister',
            name='dreg_phone_number',
            field=models.IntegerField(),
        ),
    ]
